export class ApiFieldUtils {
  public static RESPONSE_FIELD_LIST: { [key: string]: string[] } = {
    ROHINGYA_AFIS_SEARCH_JOB: [
      'finishTime',
      'id',
      'jobResult',
      'jobStatus',
      'score',
      'subjectId',
      'submitTime',
      'submitUser',
    ],
    LD_TAX_SEARCH: [
      'address',
      'districtName',
      'divisionName',
      'dob',
      'email',
      'fatherName',
      'gender',
      'holdingId',
      'holdingNo',
      'holdings',
      'landInfo',
      'motherName',
      'moujaName',
      'name',
      'nid',
      'officesName',
      'ownersInfo',
      'phone',
      'presentAddress',
      'taxClearYear',
      'upazilaName',
    ],
    BRTA_DRIVING_LICENSE_SEARCH: [
      'applyDate',
      'bloodGroup',
      'dateOfBirth',
      'expiryDate',
      'fatherName',
      'gender',
      'issueDate',
      'issuingAuthority',
      'licenseNumber',
      'licenseType',
      'mobileNo',
      'name',
      'nid',
      'permanentAddress',
      'photoUrl',
      'presentAddress',
      'renewalDate',
      'signatureUrl',
      'spouseName',
    ],
    ROHINGYA_PROFILE_SEARCH: [
      'address',
      'age',
      'creationDate',
      'dateOfBirth',
      'district',
      'fatherNameEng',
      'gender',
      'motherNameEng',
      'nameEng',
      'photo',
      'placeOfBirth',
      'policeStation',
      'referenceNo',
      'religion',
      'village',
    ],
    ESAF_SEARCH: [
      'dateOfBirth',
      'gender',
      'idNumber',
      'idType',
      'mobileNumber',
      'name',
    ],
    BIRTH_REGISTRATION_SEARCH: [
      'dateofBirth',
      'fatherNationality',
      'fatherNationalityEn',
      'fathername',
      'fathernameEn',
      'motherNationality',
      'motherNationalityEn',
      'mothername',
      'mothernameEn',
      'personname',
      'personnameEn',
      'placeofbirth',
      'placeofbirthEn',
      'sex',
    ],
    NBR_SEARCH: [
      'assesseeName',
      'boIdate',
      'boInumber',
      'contactTelephone',
      'contactTelephoneSub',
      'dob',
      'fatherName',
      'gender',
      'incorporationDate',
      'incorporationNumber',
      'motherName',
      'newTin',
      'nid',
      'oldTin',
      'passportIssueDate',
      'passportNumber',
      'smartID',
      'spouseName',
      'tinDate',
      'visaNumber',
    ],
    STUDENT_SEARCH: [
      'boardName',
      'dob',
      'eiin',
      'examName',
      'fatherName',
      'gpa',
      'gpaExceptFourth',
      'iCode',
      'id',
      'institutionName',
      'institutionThana',
      'institutionZilla',
      'letterGrade',
      'letterGradeCa',
      'motherName',
      'name',
      'passYear',
      'regNo',
      'result',
      'resultDetail',
      'rollNo',
      'session',
      'sex',
      'studentGroup',
      'studentType',
    ],
    VEHICLE_REGISTRATION_SEARCH: [
      'dateOfBirth',
      'fatherHusbendName',
      'fitnessExpDate',
      'fitnessIssueDate',
      'jointOwner',
      'jointOwnerName',
      'ladenWeight',
      'mobileNumber',
      'nationality',
      'nidNumber',
      'noOfAxle',
      'ownerAddress',
      'ownerName',
      'registrationDate',
      'registrationNumber',
      'registrationOfficeName',
      'routePermitExpDate',
      'routePermitIssueDate',
      'routePermitNumber',
      'seatingCapacity',
      'taxTokenExpDate',
      'taxTokenIssueDate',
      'unladenWeight',
      'vehicleCC',
      'vehicleClass',
      'vehicleColour',
      'vehicleNumber',
      'vehicleRegistrationNumber',
      'vehicleSeries',
      'vehicleType',
    ],
    NEIR_SEARCH: ['docId', 'docTypeId', 'imeiList', 'msisdnList'],
    FINANCE_DIVISION_SEARCH: [
      'amount',
      'bankAccountName',
      'bankAccountNumber',
      'bankAccountType',
      'bankNameEn',
      'dob',
      'elType',
      'gender',
      'issueDate',
      'mobileNo',
      'nameBn',
      'nameEn',
      'nidNo',
      'ppNo',
      'routingNo',
      'sanctionDate',
    ],
    NID_SEARCH: [
      'bloodGroup',
      'dateOfBirth',
      'father',
      'gender',
      'mother',
      'name',
      'nameEn',
      'nationalId',
      'occupation',
      'permanentAddress',
      'photo',
      'pin',
      'presentAddress',
      'spouse',
    ],
  };
  public static REQUEST_FIELD_LIST: { [key: string]: string[] } = {
    ROHINGYA_AFIS_SEARCH_JOB: [
      'leftIndex',
      'leftLittle',
      'leftMiddle',
      'leftRing',
      'leftThumb',
      'rightIndex',
      'rightLittle',
      'rightMiddle',
      'rightRing',
      'rightThumb',
    ],
    LD_TAX_SEARCH: [
      'dagNo',
      'districtId',
      'divisionId',
      'holdingId',
      'holdingNo',
      'khotianNo',
      'mobileNo',
      'moujaId',
      'nid',
      'upazilaId',
    ],
    BRTA_DRIVING_LICENSE_SEARCH: [
      'dateOfBirth',
      'fatherEn',
      'licenseNumber',
      'mobileNumber',
      'motherEn',
      'nameEn',
      'nidNumber',
      'referenceNumber',
      'spouseEn',
    ],
    ROHINGYA_PROFILE_SEARCH: [
      'address',
      'age',
      'creation_date',
      'district',
      'father_name_eng',
      'gender',
      'mother_name_eng',
      'name_eng',
      'police_station',
      'reference_no',
      'religion',
      'village',
    ],
    ESAF_SEARCH: ['nid', 'mobileNo'],
    BIRTH_REGISTRATION_SEARCH: ['ubrn'],
    NBR_SEARCH: [
      'assesseeName',
      'contactTelephoneSub',
      'incorpNumber',
      'newTin',
      'nid',
      'oldTin',
      'passportNumber',
      'smartId',
    ],
    STUDENT_SEARCH: [
      'boardName',
      'dob',
      'eiin',
      'examName',
      'fatherName',
      'gpa',
      'iCode',
      'institutionName',
      'institutionThana',
      'institutionZilla',
      'motherName',
      'name',
      'passYear',
      'regNo',
      'rollNo',
      'studentSex',
    ],
    VEHICLE_REGISTRATION_SEARCH: [
      'nidNumber',
      'registrationNumber',
      'mobileNumber',
    ],
    NEIR_SEARCH: ['docId', 'imei', 'msisdn'],
    FINANCE_DIVISION_SEARCH: ['mobileNo', 'nid'],
    NID_SEARCH: ['nid'],
  };

  public static getFieldLabel(name: string) {
    name = name.replace(/([A-Z])/g, ' $1');
    name = name.charAt(0).toUpperCase() + name.slice(1);
    return name;
  }
}
